#ifndef GR_events
#define GR_events 1

#include "GR_config.h"
#include "SUMAA_log.h"
#ifdef __cplusplus
///
extern "C" {
#endif

  enum __GRUMMP_event_codes
  {TOTAL_TIME = 50, GUI_IDLE, READ_BDRY_2D, OPTIMIZE_BDRY_2D,
   READ_BDRY_3D, READ_MESH_2D, READ_SURF_MESH, READ_MESH_3D,
   RUPPERT, RUPPERT_INIT, RUPPERT_INIT_LARGE, RUPPERT_INIT_SMALL,
   RUPPERT_LOOP, RUPPERT_BAD_CELL,
   LFS_SETUP, LFS_CHECK,
   SHEWCHUK, SHEWCHUK_HULL, SHEWCHUK_SUBSEG, SHEWCHUK_SUBFACET,
   WATSON, WATSON_NEIGHBORS, WATSON_ORDER, WATSON_INSERT, WATSON_CHECK,
   WATSON_BDRY, WATSON_BDRY_NEIGHBORS, WATSON_BDRY_ORDER,
   WATSON_BDRY_INSERT, WATSON_BDRY_CHECK, WATSON_BDRY_UNKNOWN,
   INSERT_QUEUE, INSERT_QUEUE_BUILD, INSERT_QUEUE_REFINE,
   INSERT_QUEUE_MANIP, IQE_BUILD, IQE_QUERY, WATSON_INFO,
   INIT_TRI, INIT_SURF_TRI, INIT_TETRA,
   LENGTH_SCALE, INIT_LENGTH, UPDATE_LENGTH,
   STEINER, STEINER_CELL_QUAL,
   SMOOTHING_PASSES, NET_SMOOTHING, SWAP_PASSES, NET_SWAPPING,
   INSERT_VERTEX, DELETE_VERTEX, PURGE, CLASSIFY_TETS, QUAL_ASSESS,
   TET_FIX, BDRY_TET_FIX, OUTPUT,
   PROBE1, PROBE2, PROBE3, PROBE4, PROBE5, FINAL};
  /* The last member of the enum -must- be FINAL */

  void vGRUMMPInitLogging(void);
  void vGRUMMPFinishLogging(void);
#ifdef __cplusplus
}
#endif

#endif
